---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: gitopsrvc-appstudio-shared
spec:
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: namespaces
  - group: managed-gitops.redhat.com
    identityHash: d15a5b28a3436f414a1d805d571097e917df9be27aa5cca36f728f9350af1756
    resource: gitopsdeployments
  - group: appstudio.redhat.com
    identityHash: bcdc9d37f1f51974c01c05fff50a6c0f119382504aa302c1eadca5cd38d55fd0
    resource: applications
  - group: appstudio.redhat.com
    identityHash: bcdc9d37f1f51974c01c05fff50a6c0f119382504aa302c1eadca5cd38d55fd0
    resource: applicationsnapshotenvironmentbindings
  - group: appstudio.redhat.com
    identityHash: bcdc9d37f1f51974c01c05fff50a6c0f119382504aa302c1eadca5cd38d55fd0
    resource: components
  - group: appstudio.redhat.com
    identityHash: bcdc9d37f1f51974c01c05fff50a6c0f119382504aa302c1eadca5cd38d55fd0
    resource: environments
