---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: integration-service
  namespace: integration-service
spec:
  latestResourceSchemas:
  - md5-bdbd79111419cb45ed5f46c858d8ff96.integrationtestscenarios.appstudio.redhat.com
  permissionClaims:
  - group: tekton.dev
    identityHash: 72b2990e51b1931e9fee86e67091b721a8c32f407d762fc847d9d2316a988b52
    resource: pipelineruns
  - group: appstudio.redhat.com
    identityHash: 1e7cdf08640a0e103e7f3a918e399d52e01b418b7cc70f5ad856d9716d7df050
    resource: applications
  - group: appstudio.redhat.com
    identityHash: 1e7cdf08640a0e103e7f3a918e399d52e01b418b7cc70f5ad856d9716d7df050
    resource: components
  - group: appstudio.redhat.com
    identityHash: 1e7cdf08640a0e103e7f3a918e399d52e01b418b7cc70f5ad856d9716d7df050
    resource: applicationsnapshots
  - group: appstudio.redhat.com
    identityHash: 1e7cdf08640a0e103e7f3a918e399d52e01b418b7cc70f5ad856d9716d7df050
    resource: environments
  - group: appstudio.redhat.com
    identityHash: 1e7cdf08640a0e103e7f3a918e399d52e01b418b7cc70f5ad856d9716d7df050
    resource: applicationsnapshotenvironmentbindings
  - group: appstudio.redhat.com
    identityHash: 5024ed58df4da303eadd45dac5564b58694ecf87a9aa6177a3634ce67efe76a4
    resource: releases
  - group: appstudio.redhat.com
    identityHash: 5024ed58df4da303eadd45dac5564b58694ecf87a9aa6177a3634ce67efe76a4
    resource: releaseplans
