---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: integration-service
  namespace: integration-service
spec:
  latestResourceSchemas:
  - md5-8a5fe3ad269e913b88cb0bf420c0f8a2.integrationtestscenarios.appstudio.redhat.com
  permissionClaims:
  - group: tekton.dev
    identityHash: 72b2990e51b1931e9fee86e67091b721a8c32f407d762fc847d9d2316a988b52
    resource: pipelineruns
  - group: appstudio.redhat.com
    identityHash: d8af9638b45a120f45dd1cb89f62edde2a724c1d1c50c79c47509f5d6044c61d
    resource: applications
  - group: appstudio.redhat.com
    identityHash: d8af9638b45a120f45dd1cb89f62edde2a724c1d1c50c79c47509f5d6044c61d
    resource: components
  - group: appstudio.redhat.com
    identityHash: d8af9638b45a120f45dd1cb89f62edde2a724c1d1c50c79c47509f5d6044c61d
    resource: applicationsnapshots
  - group: appstudio.redhat.com
    identityHash: d8af9638b45a120f45dd1cb89f62edde2a724c1d1c50c79c47509f5d6044c61d
    resource: environments
  - group: appstudio.redhat.com
    identityHash: d8af9638b45a120f45dd1cb89f62edde2a724c1d1c50c79c47509f5d6044c61d
    resource: applicationsnapshotenvironmentbindings
  - group: appstudio.redhat.com
    identityHash: 0f3f1dae5388cc1208ae807b70897aebb8008280b60622e0c112441faa077e25
    resource: releases
  - group: appstudio.redhat.com
    identityHash: 0f3f1dae5388cc1208ae807b70897aebb8008280b60622e0c112441faa077e25
    resource: releaseplans
