---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/psturc-org/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-pipeline-service-test-osp-nightly-masj
