---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: add-base-domain-param.yaml
    target:
      group: argoproj.io
      kind: ApplicationSet
      version: v1alpha1
  - path: gitops-service-argocd.yaml
