---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: application-service
  namespace: application-service
spec:
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: namespaces
  - group: ""
    resource: configmaps
  - group: apis.kcp.dev
    resource: apibindings
  - group: appstudio.redhat.com
    identityHash: bcdc9d37f1f51974c01c05fff50a6c0f119382504aa302c1eadca5cd38d55fd0
    resource: applications
  - group: appstudio.redhat.com
    identityHash: bcdc9d37f1f51974c01c05fff50a6c0f119382504aa302c1eadca5cd38d55fd0
    resource: snapshots
  - group: appstudio.redhat.com
    identityHash: bcdc9d37f1f51974c01c05fff50a6c0f119382504aa302c1eadca5cd38d55fd0
    resource: snapshotenvironmentbindings
  - group: appstudio.redhat.com
    identityHash: bcdc9d37f1f51974c01c05fff50a6c0f119382504aa302c1eadca5cd38d55fd0
    resource: components
  - group: appstudio.redhat.com
    identityHash: bcdc9d37f1f51974c01c05fff50a6c0f119382504aa302c1eadca5cd38d55fd0
    resource: componentdetectionqueries
  - group: appstudio.redhat.com
    identityHash: bcdc9d37f1f51974c01c05fff50a6c0f119382504aa302c1eadca5cd38d55fd0
    resource: environments
  - group: appstudio.redhat.com
    identityHash: 52e5d78255f125be1f07bce8502e8542ebda3a6854cbd8f2b65c7342fbadb316
    resource: spiaccesstokens
  - group: appstudio.redhat.com
    identityHash: 52e5d78255f125be1f07bce8502e8542ebda3a6854cbd8f2b65c7342fbadb316
    resource: spiaccesstokenbindings
