---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: application-service
  namespace: application-service
spec:
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: namespaces
  - group: ""
    resource: configmaps
  - group: appstudio.redhat.com
    identityHash: d8af9638b45a120f45dd1cb89f62edde2a724c1d1c50c79c47509f5d6044c61d
    resource: applications
  - group: appstudio.redhat.com
    identityHash: d8af9638b45a120f45dd1cb89f62edde2a724c1d1c50c79c47509f5d6044c61d
    resource: applicationsnapshots
  - group: appstudio.redhat.com
    identityHash: d8af9638b45a120f45dd1cb89f62edde2a724c1d1c50c79c47509f5d6044c61d
    resource: applicationsnapshotenvironmentbindings
  - group: appstudio.redhat.com
    identityHash: d8af9638b45a120f45dd1cb89f62edde2a724c1d1c50c79c47509f5d6044c61d
    resource: components
  - group: appstudio.redhat.com
    identityHash: d8af9638b45a120f45dd1cb89f62edde2a724c1d1c50c79c47509f5d6044c61d
    resource: componentdetectionqueries
  - group: appstudio.redhat.com
    identityHash: d8af9638b45a120f45dd1cb89f62edde2a724c1d1c50c79c47509f5d6044c61d
    resource: environments
  - group: appstudio.redhat.com
    identityHash: 2425e81231fba84327d3ae676575baebc1a04b16f3d1e645f08904bf5d210a61
    resource: spiaccesstokens
  - group: appstudio.redhat.com
    identityHash: 2425e81231fba84327d3ae676575baebc1a04b16f3d1e645f08904bf5d210a61
    resource: spiaccesstokenbindings
