---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-service-argocd-repo-server
  namespace: gitops-service-argocd
spec:
  template:
    spec:
      containers:
      - name: argocd-repo-server
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
      initContainers:
      - name: copyutil
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
