apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: gitops-service-argocd
  namespace: gitops-service-argocd
spec:
  server:
    env:
      - name: ARGOCD_EXEC_TIMEOUT
        value: 5m
  repo:
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
