apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/konflux-ci/integration-service/config/default?ref=4a1be0120d40c46a6a80826467bafffc83768212
  - https://github.com/konflux-ci/integration-service/config/snapshotgc?ref=4a1be0120d40c46a6a80826467bafffc83768212
images:
  - name: quay.io/redhat-appstudio/integration-service
    newName: quay.io/redhat-user-workloads/rhtap-integration-tenant/integration-service/integration-service@sha256
    newTag: 75c4356e8fdefea826e067b18e0f8d816911d547f48bd876e5b9fa89c50d517f
configMapGenerator:
  - name: integration-config
    literals:
      - CONSOLE_NAME="Konflux Dev version"
      - CONSOLE_URL=""
      - CONSOLE_URL_TASKLOG=""
  - name: pipelinerun-options
    literals:
      - PIPELINE_TIMEOUT="6h"
      - TASKS_TIMEOUT="4h"
      - FINALLY_TIMEOUT="2h"
namespace: integration-service
patches:
  - path: manager_resources_patch.yaml
  - path: snapshotgc_inputs_patch.yaml
    target:
      kind: CronJob
      name: snapshot-garbage-collector
components:
  - ../rh-certs
