apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/build-service/config/default?ref=2dee6cfe6fe436a921ea4589f0e4bf7c32f802d2

namespace: build-service

images:
- name: quay.io/konflux-ci/build-service
  newName: quay.io/konflux-ci/build-service
  newTag: 2dee6cfe6fe436a921ea4589f0e4bf7c32f802d2

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
