apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/host
  - ../../base/member
  - ../../base/all-clusters
  - ../../base/quality-dashboard
namespace: konflux-public-staging
patches:
  - path: migration.patch.yaml
    target:
      kind: ApplicationSet
      version: v1alpha1
