---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: build-service
  namespace: build-service
spec:
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: configmaps
  - group: ""
    resource: namespaces
  - group: ""
    resource: events
  - group: ""
    resource: serviceaccounts
  - group: tekton.dev
    identityHash: 72b2990e51b1931e9fee86e67091b721a8c32f407d762fc847d9d2316a988b52
    resource: pipelineruns
  - group: appstudio.redhat.com
    identityHash: 4de302c75f81a9a8ea8791571fadb207c74834a386436dc491dc13d708a5175c
    resource: components
  - group: appstudio.redhat.com
    identityHash: 4de302c75f81a9a8ea8791571fadb207c74834a386436dc491dc13d708a5175c
    resource: applications
  - group: appstudio.redhat.com
    identityHash: 4de302c75f81a9a8ea8791571fadb207c74834a386436dc491dc13d708a5175c
    resource: applicationsnapshots
