---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: build-service
  namespace: build-service
spec:
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: configmaps
  - group: ""
    resource: namespaces
  - group: ""
    resource: events
  - group: ""
    resource: serviceaccounts
  - group: apis.kcp.dev
    resource: apibindings
  - group: tekton.dev
    identityHash: 72b2990e51b1931e9fee86e67091b721a8c32f407d762fc847d9d2316a988b52
    resource: pipelineruns
  - group: pipelinesascode.tekton.dev
    identityHash: 72b2990e51b1931e9fee86e67091b721a8c32f407d762fc847d9d2316a988b52
    resource: repositories
  - group: appstudio.redhat.com
    identityHash: 3950ce381a8478fc0446eedd1f7520e6bd406823854d82f295d871b9e620b9b8
    resource: components
  - group: appstudio.redhat.com
    identityHash: 3950ce381a8478fc0446eedd1f7520e6bd406823854d82f295d871b9e620b9b8
    resource: applications
  - group: appstudio.redhat.com
    identityHash: 3950ce381a8478fc0446eedd1f7520e6bd406823854d82f295d871b9e620b9b8
    resource: snapshots
