apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: build
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source: # This will be replaced with a reference to your fork of this repo (see hack/patch-apps-for-dev.sh)
    repoURL: https://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@github.com/psturc-org/infra-deployments.git
    targetRevision: preview-main-1657283152
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://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@github.com/psturc-org/infra-deployments.git
    targetRevision: preview-main-1657283152
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: has
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://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@github.com/psturc-org/infra-deployments.git
    targetRevision: preview-main-1657283152
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: release
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://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@github.com/psturc-org/infra-deployments.git
    targetRevision: preview-main-1657283152
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: integration
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://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@github.com/psturc-org/infra-deployments.git
    targetRevision: preview-main-1657283152
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://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@github.com/psturc-org/infra-deployments.git
    targetRevision: preview-main-1657283152
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: e2e-tests
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://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@github.com/psturc-org/infra-deployments.git
    targetRevision: preview-main-1657283152
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-registration
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://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@github.com/psturc-org/infra-deployments.git
    targetRevision: preview-main-1657283152
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quality-dashboard
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://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@github.com/psturc-org/infra-deployments.git
    targetRevision: preview-main-1657283152
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-contract
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://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@github.com/psturc-org/infra-deployments.git
    targetRevision: preview-main-1657283152
