resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/redhat-appstudio/release-service/config/default?ref=9e166788e197f8556ad73d1e80edbd504b6266b2
  - release-pipeline-resources-clusterrole.yaml
  - release-team.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/release-service
    newName: quay.io/damoreno/release-service
    newTag: rhtaprel298
namespace: release-service
patches:
  - path: ./manager_resources_patch.yaml
